#!/usr/bin/env python3
"""build-exemplar-gallery.py — auto-generate auditor/exemplars/README.md.

Walks every `auditor/exemplars/<slug>.md`, parses its frontmatter
(slug, repo, audited, score, exemplifies), and writes a deterministic
index with three views: by rule, by score, by repo.

Run after every exemplar write — see `.github/workflows/auditor-exemplar.yml`
for the live wiring. Also runs from CI as a freshness check: if the
script's output differs from the committed README.md, the gallery is
stale.

Output is deterministic — sorted alphabetically and numerically, no
timestamps in the body except per-exemplar `audited` dates which come
from the source frontmatter. The script is safe to run repeatedly.

Exit codes:
  0 — gallery written (or unchanged when --check)
  1 — gallery would change (only with --check)
  2 — internal error (e.g., exemplars dir missing AND --check passed)

Usage:
  python3 auditor/scripts/build-exemplar-gallery.py
  python3 auditor/scripts/build-exemplar-gallery.py --check
  python3 auditor/scripts/build-exemplar-gallery.py --self-test
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
EXEMPLARS_DIR = REPO_ROOT / "auditor" / "exemplars"
OUTPUT_PATH = EXEMPLARS_DIR / "README.md"


@dataclass
class Exemplar:
    slug: str
    repo: str
    audited: str
    score: int
    exemplifies: list[str]
    path: Path

    @property
    def relpath(self) -> str:
        """Relative path from auditor/exemplars/README.md to this exemplar."""
        return self.path.name


def parse_frontmatter(text: str) -> dict[str, object]:
    """Extract YAML-ish frontmatter values. Stdlib-only — no yaml import.

    Returns {} if no frontmatter found. Tolerant of missing fields.
    """
    fm_match = re.match(r"^---\n(.*?)\n---", text, re.DOTALL)
    if not fm_match:
        return {}
    fm = fm_match.group(1)
    out: dict[str, object] = {}
    # scalar fields
    for key in ("slug", "repo", "audited", "commit_sha", "score"):
        m = re.search(rf"^{key}:\s*([\S]+)", fm, re.MULTILINE)
        if m:
            out[key] = m.group(1).strip().strip('"').strip("'")
    # exemplifies: list
    in_list = False
    rules: list[str] = []
    for line in fm.splitlines():
        if re.match(r"^exemplifies:\s*$", line):
            in_list = True
            continue
        if not in_list:
            continue
        m = re.match(r"^[ \t]+-[ \t]+(R\d{2})\b", line)
        if m:
            rules.append(m.group(1))
            continue
        # Top-level key (no indent) ends the list. Blank lines are tolerated.
        if line and not line.startswith((" ", "\t")):
            in_list = False
    out["exemplifies"] = rules
    return out


def load_exemplars(directory: Path) -> list[Exemplar]:
    """Walk exemplars dir, return list sorted by slug. Skips README.md.

    Malformed files are silently dropped — the gallery is best-effort, not
    a validator. Use `nlpm-check` or `validate-rule-ids.py` for strictness.
    """
    if not directory.exists():
        return []
    result: list[Exemplar] = []
    for path in sorted(directory.glob("*.md")):
        if path.name == "README.md":
            continue
        try:
            text = path.read_text(errors="ignore")
        except OSError:
            continue
        fm = parse_frontmatter(text)
        slug = fm.get("slug") or path.stem
        repo = fm.get("repo")
        if not repo:
            # No repo means this isn't a real exemplar — skip.
            continue
        try:
            score = int(fm.get("score") or 0)
        except (TypeError, ValueError):
            score = 0
        result.append(Exemplar(
            slug=str(slug),
            repo=str(repo),
            audited=str(fm.get("audited") or "?"),
            score=score,
            exemplifies=list(fm.get("exemplifies") or []),
            path=path,
        ))
    return sorted(result, key=lambda e: e.slug)


def render_gallery(exemplars: list[Exemplar]) -> str:
    """Render the gallery markdown. Deterministic — same input → same output."""
    lines: list[str] = []
    lines.append("# NLPM Exemplar Gallery")
    lines.append("")
    lines.append(
        "Real-world repos whose NL artifacts pass the 50-rule audit at a "
        "high score with no PR-worthy bugs. Each exemplar cites which "
        "rules its body demonstrates with concrete evidence."
    )
    lines.append("")
    lines.append(
        "Generated by `auditor/scripts/build-exemplar-gallery.py` — do "
        "not hand-edit. Runs after every `auditor-exemplar.yml` execution."
    )
    lines.append("")

    if not exemplars:
        lines.append("_No exemplars yet. The first one lands as soon as a "
                     "pipeline audit scores ≥ 90 with security != BLOCKED._")
        lines.append("")
        return "\n".join(lines) + "\n"

    lines.append(f"**Total exemplars:** {len(exemplars)}")
    # Unique rules covered
    rules_covered: set[str] = set()
    for ex in exemplars:
        rules_covered.update(ex.exemplifies)
    lines.append(f"**Rules with ≥1 exemplar:** {len(rules_covered)}")
    lines.append("")

    # === By score (descending) ===
    lines.append("## By score")
    lines.append("")
    lines.append("| Score | Repo | Audited | Exemplifies |")
    lines.append("|------:|------|---------|-------------|")
    by_score = sorted(exemplars, key=lambda e: (-e.score, e.slug))
    for ex in by_score:
        rules = ", ".join(ex.exemplifies) or "—"
        lines.append(
            f"| {ex.score} | [{ex.repo}]({ex.relpath}) | {ex.audited} | {rules} |"
        )
    lines.append("")

    # === By rule (each rule → exemplars that demonstrate it) ===
    lines.append("## By rule")
    lines.append("")
    lines.append(
        "When a rule below has at least one exemplar, the rule entry in "
        "`skills/nlpm/rules/SKILL.md` can cite it as a real-world reference. "
        "See `auditor/scripts/propose-rule-citations.py` for the auto-PR path."
    )
    lines.append("")
    by_rule: dict[str, list[Exemplar]] = defaultdict(list)
    for ex in exemplars:
        for rid in ex.exemplifies:
            by_rule[rid].append(ex)
    if not by_rule:
        lines.append("_No rules cited yet._")
        lines.append("")
    else:
        lines.append("| Rule | Exemplar count | Repos |")
        lines.append("|------|---------------:|-------|")
        for rid in sorted(by_rule.keys()):
            repos_list = ", ".join(
                f"[{ex.repo}]({ex.relpath})" for ex in by_rule[rid]
            )
            lines.append(f"| {rid} | {len(by_rule[rid])} | {repos_list} |")
        lines.append("")

    # === By repo (alphabetical) ===
    lines.append("## By repo")
    lines.append("")
    lines.append("| Repo | Score | Audited | Exemplifies |")
    lines.append("|------|------:|---------|-------------|")
    for ex in exemplars:  # already sorted by slug
        rules = ", ".join(ex.exemplifies) or "—"
        lines.append(
            f"| [{ex.repo}]({ex.relpath}) | {ex.score} | {ex.audited} | {rules} |"
        )
    lines.append("")

    return "\n".join(lines) + "\n"


def self_test() -> int:
    """Inline tests for parse_frontmatter and render_gallery."""
    import tempfile

    fm = parse_frontmatter("""---
slug: foo-bar
repo: foo/bar
audited: 2026-05-14
commit_sha: abc1234
score: 92
exemplifies:
  - R04
  - R05
  - R06
metadata: ignored
---

# body
""")
    assert fm.get("slug") == "foo-bar", fm
    assert fm.get("repo") == "foo/bar", fm
    assert fm.get("score") == "92", fm  # raw string at this layer
    assert fm.get("exemplifies") == ["R04", "R05", "R06"], fm

    # Empty input
    assert parse_frontmatter("no frontmatter here") == {}

    # Render with empty list
    out = render_gallery([])
    assert "No exemplars yet" in out
    assert out.startswith("# NLPM Exemplar Gallery")

    # Render with multiple exemplars, verify determinism
    with tempfile.TemporaryDirectory() as td:
        d = Path(td) / "exemplars"
        d.mkdir()
        for slug, repo, score, rules in [
            ("a-foo", "a/foo", 94, ["R04", "R05"]),
            ("b-bar", "b/bar", 90, ["R04", "R06"]),
            ("c-baz", "c/baz", 92, ["R07"]),
        ]:
            (d / f"{slug}.md").write_text(f"""---
slug: {slug}
repo: {repo}
audited: 2026-05-14
score: {score}
exemplifies:
{chr(10).join(f"  - {r}" for r in rules)}
---
""")
        exemplars = load_exemplars(d)
        assert len(exemplars) == 3
        # Sort order: by slug
        assert [e.slug for e in exemplars] == ["a-foo", "b-bar", "c-baz"]
        out = render_gallery(exemplars)
        # Verify by-score sorting (desc): 94, 92, 90
        score_block = out.split("## By score")[1].split("## By rule")[0]
        idx_94 = score_block.find("| 94 |")
        idx_92 = score_block.find("| 92 |")
        idx_90 = score_block.find("| 90 |")
        assert 0 < idx_94 < idx_92 < idx_90, (idx_94, idx_92, idx_90)
        # R04 appears in 2 exemplars
        assert "| R04 | 2 |" in out
        # Determinism: render twice, identical
        assert render_gallery(exemplars) == out
    print("self-test PASS")
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    p.add_argument("--check", action="store_true",
                   help="Exit 1 if the gallery would change (CI freshness check)")
    p.add_argument("--self-test", action="store_true")
    p.add_argument("--exemplars-dir", type=Path, default=EXEMPLARS_DIR)
    p.add_argument("--output", type=Path, default=OUTPUT_PATH)
    args = p.parse_args(argv)

    if args.self_test:
        return self_test()

    exemplars = load_exemplars(args.exemplars_dir)
    rendered = render_gallery(exemplars)

    if args.check:
        if not args.output.exists():
            if not exemplars:
                # Nothing to publish, nothing committed — clean.
                return 0
            print(f"DRIFT: gallery missing at {args.output}", file=sys.stderr)
            return 1
        existing = args.output.read_text()
        if existing != rendered:
            print(f"DRIFT: {args.output} is stale — re-run without --check", file=sys.stderr)
            return 1
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)
    print(f"wrote {args.output} ({len(exemplars)} exemplars, "
          f"{sum(1 for _ in exemplars)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
